- .github/pull_request_template.md
- fstab.yaml
- package.json
- Update PR template
- Update fstab sharepoint
- Add lint:fix
Fix #1 
Test URLs:
- After: https://initialsetup--esri--aemsites.hlx.live/
> Initial setup

- tools/sidekick/config.json
Fix #7
Test URLs:
- After: https://7-create-config-json-library-sidekick--esri--aemsites.hlx.live/
> #7: Create config.json

- blocks/media-gallery/media-gallery.css
- blocks/media-gallery/media-gallery.js
- head.html
- styles/styles.css
Partial fix for #5 #6 
Test URLs:
- Before: https://main--esri--aemsites.hlx.live/drafts/shared/media-gallery
- After: https://add-media-gallery-block--esri--vladciocoiu.hlx.live/drafts/shared/media-gallery
> Add media gallery block

- blocks/media-gallery/media-gallery.js
- scripts/dom-helpers.js
Fix #5 #6
Test URLs:
- Before: https://main--esri--aemsites.hlx.live/drafts/shared/media-gallery
- After: https://add-dom-helpers--esri--vladciocoiu.hlx.live/drafts/shared/media-gallery
> Add and use dom-helpers functions

- blocks/media-gallery/media-gallery.css
- scripts/scripts.js
- styles/styles.css
Fix #11 
Test URLs:
- Before: https://main--esri--aemsites.hlx.live/drafts/shared/media-gallery
- After: https://add-video-lightbox--esri--aemsites.hlx.live/drafts/shared/media-gallery
> Implement video lightbox

- blocks/quote/quote.css
- blocks/quote/quote.js
- styles/styles.css
Fix #27 
Test URLs:
- Original: https://www.esri.com/en-us/capabilities/imagery-remote-sensing/capabilities/management
- Before: https://main--esri--aemsites.hlx.live/drafts/vciocoiu/quote
- After: https://add-quote-block--esri--aemsites.hlx.live/drafts/vciocoiu/quote
> Create quote block

- .eslintrc.js
- .stylelintrc.json
- blocks/header/header.css
- blocks/hero/hero.css
- blocks/media-gallery/media-gallery.css
- blocks/quote/quote.css
- styles/styles.css
Fix #36 
Changes made:
- Added ESRI base styles, spacing, opacity variables.
- Updated the hard coded values to calcite variables in hero,media gallery,quote css files.
Test URLs:
- After: https://esri-base-styles--esri--aemsites.hlx.live/en-us/about/about-esri/overview
> #36-Added ESRI base styles and updated existing hard coded values

- blocks/text/text.css
- blocks/text/text.js
- styles/styles.css
Fix #32 
Test URLs:
Original: https://www.esri.com/en-us/about/about-esri/overview
Before: https://main--esri--aemsites.hlx.live/en-us/about/about-esri/overview
After: https://esri-text-pattern--esri--aemsites.hlx.page/drafts/shared/esri-text
> #32 - Esri text pattern

- blocks/cards/cards.css
- blocks/cards/cards.js
- blocks/video-cards/video-cards.css
- blocks/video-cards/video-cards.js
- scripts/scripts.js
- styles/styles.css
Fix #20 
Test URLs:
- After: https://add-cards--esri--aemsites.hlx.live/en-us/about/about-esri/overview
- Original: https://www.esri.com/en-us/digital-transformation/overview
- Before: https://main--esri--aemsites.hlx.live/en-us/digital-transformation/overview
- After: https://add-cards--esri--aemsites.hlx.live/en-us/digital-transformation/overview
> Add cards block

- .stylelintrc.json
- CODING_STANDARD.md
Fix #49 
Test URLs:
- After: https://test-stylelint--esri--aemsites.hlx.live/en-us/about/about-esri/overview
> Test stylelint

- blocks/tabs/tabs.css
This reverts commit 6a1c2c31cd7339bd29831120afff7975b0d8b324.
Test URLs:
- After: https://fix-lint--esri--aemsites.hlx.live/en-us/about/about-esri/overview
> Fix lint issues

- .stylelintrc.json
- blocks/tabs/tabs.css
Fix #52 
Test URLs:
- Before: https://main--esri--aemsites.hlx.live/en-us/about/about-esri/overview#education
- After: https://tabs-update--esri--aemsites.hlx.live/en-us/about/about-esri/overview#education
Add nesting level restriction to Stylelint
Flatten tabs.css to 3 levels; update color vars
> #52 Tabs update

- .stylelintrc.json
- blocks/cards/cards.css
- blocks/columns/columns.css
- blocks/footer/footer.css
- blocks/fragment/fragment.css
- blocks/header/header.css
- blocks/hero/hero.css
- blocks/media-gallery/media-gallery.css
- blocks/quote/quote.css
- blocks/text/text.css
- blocks/video-cards/video-cards.css
- package-lock.json
- package.json
Fix #59 
Test URLs:
- After: https://logical--esri--aemsites.hlx.live/en-us/about/about-esri/overview
> #59 - Add Stylelint and update css

- blocks/tabs-cards/tabs-cards.css
- blocks/tabs-cards/tabs-cards.js
Fix #60 
Test URLs:
- Original: https://www.esri.com/en-us/about/about-esri/mea-central-asia
- Before: https://main--esri--aemsites.hlx.live/drafts/vciocoiu/tabs-cards
- After: https://add-tabs-cards--esri--aemsites.hlx.live/drafts/vciocoiu/tabs-cards
> Implement tabs-cards component

- .stylelintrc.json
- blocks/tabs-cards/tabs-cards.css
- blocks/tabs/tabs.css
- styles/styles.css
Fix #59 
Test URLs:
- After: https://add-logical--esri--aemsites.hlx.live/en-us/about/about-esri/overview
> #59 - Add Stylelint logical property checks

- head.html
- scripts/delayed.js
Fix #43 
Test URLs:
- After: https://launch--esri--aemsites.hlx.live/en-us/about/about-esri/overview
> #43 feat: add Launch dev script

- .stylelintrc.json
Test URLs:
- After: https://fix-css404--esri--aemsites.hlx.live/en-us/about/about-esri/overview
> Fix missing css

- blocks/tabs-cards/tabs-cards.css
- blocks/tabs-cards/tabs-cards.js
- blocks/tabs/tabs.css
- blocks/tabs/tabs.js
Fix #60 
Test URLs:
- Original: https://www.esri.com/en-us/about/about-esri/mea-central-asia#esri-events
- Before: https://main--esri--aemsites.hlx.live/drafts/vciocoiu/tabs-cards
- After: https://combine-tabs-cards--esri--aemsites.hlx.live/drafts/vciocoiu/tabs-cards
> Nest tabs and tabs-cards components

- blocks/hero/hero.css
- blocks/hero/hero.js
Fix https://github.com/aemsites/esri/issues/83
Test URLs:
- Before: [https://main--esri--aemsites.hlx.live/en-us/about/about-esri/overview]( https://main--esri--aemsites.hlx.live/en-us/about/about-esri/overview)
- After: https://hero-banner-video-fix--esri--aemsites.hlx.live/en-us/about/about-esri/overview
> 83 Hero Banner - Fix background positioning

- blocks/hero/hero.js
Test URLs:
- After: https://eagerloadheroimages--esri--aemsites.hlx.live/en-us/about/about-esri/overview
> Eager load hero images

- blocks/mosaic-reveal/mosaic-reveal.css
- blocks/mosaic-reveal/mosaic-reveal.js
Fix #74 
Test URLs:
- Original: https://www.esri.com/en-us/about/about-esri/mea-central-asia
- Before: https://main--esri--aemsites.hlx.live/drafts/vciocoiu/mosaic-reveal
- After: https://add-mosaic-reveal--esri--aemsites.hlx.live/drafts/vciocoiu/mosaic-reveal
> Implement mosaic reveal block

- styles/styles.css
Fix #78
Test URLs:
- Before: https://main--esri--aemsites.hlx.page/en-us/about/about-esri/overview
- After: https://style-update--esri--aemsites.hlx.page/en-us/about/about-esri/overview
> #78 refactor: update CSS styles to use design system

- blocks/sidedrawer/sidedrawer.css
- blocks/sidedrawer/sidedrawer.js
Fix #85 
Test URLs:
- Before: https://main--esri--aemsites.hlx.page/en-us/capabilities/imagery-remote-sensing/overview
- After: https://sidedrawer--esri--aemsites.hlx.live/drafts/shared/sidedrawer
Notes:
- Added sidedrawer functionality.
- Should add the form inside once a way is figured out.
>  #85-side drawer intial commit

- blocks/cards/cards.css
- blocks/cards/cards.js
Fix #64 
Test URLs:
- Original: https://www.esri.com/en-us/digital-twin/overview
- Before: https://main--esri--aemsites.hlx.live/en-us/digital-twin/overview
- After: https://cards-simple-variation--esri--aemsites.hlx.live/drafts/shared/cards-simple
> #64-Cards simple variation

- blocks/storyteller/storyteller.css
- blocks/storyteller/storyteller.js
Fix https://github.com/aemsites/esri/issues/13
Test URLs:
- After: https://storyteller-comp--esri--aemsites.hlx.live/
> Implement Storyteller block

- blocks/contact-local-office/contact-local-office.css
- blocks/contact-local-office/contact-local-office.js
Fix #103 
Test URLs:
- Before: https://main--esri--aemsites.hlx.page/en-us/about/about-esri/americas
- After: https://about-us--esri--aemsites.hlx.page/en-us/about/about-esri/americas
> feat: add contact local office section

- blocks/hero/hero.css
- blocks/hero/hero.js
- blocks/storyteller/storyteller.css
- blocks/storyteller/storyteller.js
Fix #108 
Test URLs:
- Original: https://www.esri.com/en-us/about/about-esri/technology
- After: https://hero-variation-two--esri--aemsites.hlx.live/
> Hero - Foreground Image Markup Position is not static

- blocks/storyteller/storyteller.css
- blocks/storyteller/storyteller.js
Fix #104
Test URLs:
- After: https://storyteller-playbutton--esri--aemsites.hlx.live/
> Storyteller - add playhead functionality for animated video

- styles/styles.css
Fix #116
Test URLs:
- After: https://box-size--esri--aemsites.hlx.live/
> feat: fix box-sizing issue in styles.css

- blocks/local-navigation/local-navigation.css
- blocks/local-navigation/local-navigation.js
- styles/styles.css
Fix #75 
Test URLs:
- After: https://local-navigation--esri--aemsites.hlx.live/
> Local Navigation - Implementation

- blocks/local-navigation/local-navigation.css
- blocks/local-navigation/local-navigation.js
- styles/styles.css
Similar to the authoring experience in AEM, nav title and register button are authoreable feature options. Nav title is aligned to far left of navigation and register/login button is aligned to far right of navigation.
Fix #120 
Test URLs:
- After: https://local-nav-titlepage--esri--aemsites.hlx.live/
> Local Navigation - Nav Title Feature Option

- blocks/form/form.css
- blocks/form/form.js
- head.html
Fix #54 
Test URLs:
- Original: https://www.esri.com/en-us/capabilities/imagery-remote-sensing/capabilities/management
- Before: https://main--esri--aemsites.hlx.live/en-us/capabilities/imagery-remote-sensing/capabilities/management
- Draft: https://add-form-block--esri--aemsites.hlx.live/drafts/vciocoiu/form
- After: https://add-form-block--esri--aemsites.hlx.live/en-us/capabilities/imagery-remote-sensing/capabilities/management
> Implement One Form block

- blocks/centered-content-switcher/centered-content-switcher.css
- blocks/centered-content-switcher/centered-content-switcher.js
- styles/styles.css
Fix #93 
Test URLs:
- After: https://add-centered-content-switcher--esri--aemsites.hlx.live/en-us/about/about-esri/americas
> Implement Centered Content Switcher block

- blocks/contact-local-office/contact-local-office.css
- blocks/contact-local-office/contact-local-office.js
- scripts/scripts.js
- styles/styles.css
Fix #<gh-issue-id>
Test URLs:
- Original: https://www.esri.com/en-us/about/about-esri/asia-pacific
- Before: https://main--esri--aemsites.hlx.live/en-us/about/about-esri/asia-pacific
- After: https://about-us-video--esri--aemsites.hlx.live/drafts/asimon/about-asia-pacific
> About us video

- blocks/location-presence/location-presence.css
- blocks/location-presence/location-presence.js
Fix #<gh-issue-id>
Test URLs:
- Before: https://main--esri--aemsites.hlx.live/en-us/about-esri/americas
- After: https://about-last-contact-block--esri--aemsites.hlx.live/drafts/asimon/location-presence
> locations about contact block

- blocks/storyteller/storyteller.css
- blocks/storyteller/storyteller.js
Fix #121
Test URLs:
- After: https://storyteller-variance--esri--aemsites.hlx.live/
> Storyteller - Console Errors / Authoring Variants

- scripts/ffetch.js
Fix #131 
Test URLs:
- After: https://fetch--esri--aemsites.hlx.live/
> feat: add ffetch.js for indexing

- blocks/header/header.css
- blocks/header/header.js
- scripts/dom-helpers.js
- scripts/scripts.js
Fix #94
Test URLs:
- After: https://lang--esri--aemsites.hlx.live/
> Add alternate language links to head, enables Global Nav lang switcher

- blocks/centered-content-switcher/centered-content-switcher.js
Fix #93 
Test URLs:
- After: https://fix-centered-content-switcher--esri--aemsites.hlx.live/en-us/about/about-esri/americas
> Fix Centered Content Switcher issue

- blocks/centered-content-switcher/centered-content-switcher.css
- blocks/centered-content-switcher/centered-content-switcher.js
Fix #142 
Test URLs:
- After: https://improve-centered-content-switcher--esri--aemsites.hlx.live/en-us/about/about-esri/americas
- After: https://improve-centered-content-switcher--esri--aemsites.hlx.live/en-us/about/about-esri/mea-central-asia
- After: https://improve-centered-content-switcher--esri--aemsites.hlx.live/en-us/capabilities/indoor-gis/capabilities/indoor-positioning-navigation
> Fix Centered Content Switcher

- blocks/cards/cards.css
- blocks/cards/cards.js
- styles/styles.css
Fix #95 
Test URLs:
- After: https://cards-standard--esri--aemsites.hlx.page/en-us/about/about-esri/americas
> Cards Standard Variation

- scripts/delayed.js
Fix #151
Test URLs:
- After: https://datalayer--esri--aemsites.hlx.live/en-us/about/about-esri/overview
> feat: push page properties to datalayer

- blocks/storyteller/storyteller.css
- scripts/delayed.js
- scripts/scripts.js
Append analytic attributes to block links.
Fix #147
Test URLs:
- After: https://links-analytics-147--esri--aemsites.hlx.live/
> Append Analytics to Block Links

- blocks/map/map.css
- blocks/map/map.js
Fix #<gh-issue-id>
Test URLs:
- After: https://map-block-fix--esri--aemsites.hlx.live/en-us/about/about-esri/americas
> fix: map block selection and styling

- scripts/delayed.js
Fix #147
Test URLs:
- After: https://push-datalayer--esri--aemsites.hlx.live/
> Data Layer - Listen for link click events 

- fstab.yaml
Fix #
Test URLs:
- After: https://sharepoint--esri--aemsites.hlx.live/
> feat: testing mountpoint

- fstab.yaml
Fix #<gh-issue-id>
Test URLs:
- After: https://spMount--esri--aemsites.hlx.live/
> feat: update mountpoint
